chore: add Fatal and FatalCtx
birdie-ai/golibs pull request #17
Opened 2023-07-21 18:51 UTC by guilherme-santos

2023-07-22 11:59 UTC, katcipis requested changes
Good idea, typo on the function name :heart:

2023-07-22 11:59 UTC, katcipis commented on slog/slog.go
> +func FataCtx(ctx context.Context, msg string, args ...any) {
```suggestion
// FatalCtx is equivalent to ErrorCtx() followed by a call to os.Exit(1).
func FatalCtx(ctx context.Context, msg string, args ...any) {
```

2023-07-22 12:27 UTC, guilherme-santos commented on slog/slog.go
> +func FataCtx(ctx context.Context, msg string, args ...any) {
Opsie.

2023-07-22 14:38 UTC, katcipis approved these changes

2023-07-24 07:20 UTC, lfritz approved these changes

2023-07-24 11:30 UTC, merged